"""remove unique

Revision ID: 466d37679b54
Revises: ea2ad1ceb27d
Create Date: 2025-10-04 21:49:51.733182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466d37679b54'
down_revision = 'ea2ad1ceb27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_player_username'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_player_username'), ['username'])

    # ### end Alembic commands ###
