"""allow_multiple_teams_per_dropzone

Revision ID: ea2ad1ceb27d
Revises: 84922776c3a2
Create Date: 2025-10-04 17:37:36.283785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2ad1ceb27d'
down_revision = '84922776c3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dropzone_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_assignment_game_dropzone'), type_='unique')
        batch_op.create_unique_constraint('uq_assignment_game_dropzone_team', ['game_id', 'dropzone_id', 'team_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dropzone_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_assignment_game_dropzone_team', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_assignment_game_dropzone'), ['game_id', 'dropzone_id'])

    # ### end Alembic commands ###
